_base_ = './reppoints_v2_mobilenet_fpn_giou_mstrain_2x_coco.py'
model = dict(
    neck=dict(
        in_channels=[24, 32, 96, 320],
        out_channels=128),
    bbox_head=dict(
        in_channels=128,
        feat_channels=128,
        point_feat_channels=128))
